name: Docker CI
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: chekcout code
        uses: actions/checkout@v4
      
      - name: Build Docker Image
        run: docker build -t my-application:${{github.sha}} .
  
      - name: Show Docker Images
        run: docker images
